version: '3'
services:

  #PHP Service
  app1:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app1
      SERVICE_TAGS: dev1
    working_dir: /var/www
    volumes:
      - ./app/:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    command: nodemon public/script1.php


  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./app/:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - "app1:app1"
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge
